LavornCom/Models/Kategoriler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavornCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kategoriler()
        {
            this.Urunler = new HashSet<Urunler>();
        }
    
        public int KategoriId { get; set; }
        public string KategoriAd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urunler> Urunler { get; set; }
    }
}

LavornCom/Models/Markalar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavornCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Markalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Markalar()
        {
            this.Urunler = new HashSet<Urunler>();
        }
    
        public int Id { get; set; }
        public string MarkaAd { get; set; }
        public string Aciklama { get; set; }
        public string MarkaPicUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urunler> Urunler { get; set; }
    }
}

LavornCom/Models/Urunler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavornCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.Yorumlar1 = new HashSet<Yorumlar>();
        }
    
        public int Id { get; set; }
        public string UrunAd { get; set; }
        public string Aciklama { get; set; }
        public decimal UrunFiyat { get; set; }
        public int Stok { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public int KategoriId { get; set; }
        public int MarkaId { get; set; }
        public Nullable<int> YorumId { get; set; }
        public string ResimUrl { get; set; }
        public Nullable<int> ResimId { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Markalar Markalar { get; set; }
        public virtual Yorumlar Yorumlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorumlar> Yorumlar1 { get; set; }
    }
}

LavornCom/Models/Yorumlar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LavornCom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yorumlar()
        {
            this.Urunler = new HashSet<Urunler>();
        }
    
        public int Id { get; set; }
        public string YorumcuAd { get; set; }
        public string Mail { get; set; }
        public bool IsActive { get; set; }
        public int UrunId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urunler> Urunler { get; set; }
        public virtual Urunler Urunler1 { get; set; }
    }
}

LavornCom/Controllers/UrunlerController.cs
using LavornCom.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace EmreGiyim.Controllers
{
    public class UrunlerController : Controller
    {
        DB_109003_lavornEntities db = new DB_109003_lavornEntities();

        // GET: UrunDetay
        public ActionResult Index()
        {
            return View();
        }
       
        public ActionResult Detay(int id)
        {
            var uruns = db.Urunler.FirstOrDefault(x => x.Id == id);
            return View(uruns);

        }
        public ActionResult Kategoriler(int id)
        {
            var Kategori = db.Urunler.Where(x => x.Id == id);
            return View(Kategori);

        }
        public ActionResult UrunGetir()
        {
            var runs = db.Urunler.Where(x => x.IsActive == true).ToList();
            return View(runs);
            
        }
        public ActionResult Markalar(int id)
        {
            var markalar = db.Urunler.Where(x => x.Id == id);
            return View(markalar);
        }

        public ActionResult Yorumlar(/*string yorum,*/ string mailadres, string yorumcuad, int urunıd)
        {
            Yorumlar yrm = new Yorumlar();
            //yrm. = yorum;
            yrm.Mail = mailadres;
            yrm.YorumcuAd = yorumcuad;
            yrm.UrunId = urunıd;
            //yrm.Urunler.Where(x => x.UrunId ==ıs) == urunıd;
            db.Yorumlar.Add(yrm);
            db.SaveChanges();
            return View();

        }
        //public ActionResult YorumlarListe(int id)
        //{ var sonuc = db.Yorumlar.Where(x => x.Yorum == null);
        //    if (sonuc==null )
        //    {
        //        string hata = "Henüz hiç yorum yapılmamış";
        //        ViewBag.hata = hata;
        //        return View(hata);
        //    }
        //    else { 
        //    var yorumlarliste = db.Yorumlar.Where(x => x.UrunId ==id ).ToList();
        //    return View(yorumlarliste);
        //    }
        //}
        //[Authorize]
        //[HttpPost]
        //public ActionResult Detay(int id, string UrunAdi, decimal Fiyat, int Adet,string mail)
        //{
        //    Sepet ms = new Sepet();
        //    ms.UrunId = id;
        //    ms.UrunAd = UrunAdi;
        //    ms.UrunFiyat = Fiyat;
        //    ms.Adet = Adet;
        //    ms.MusteriMail = mail;
        //    db.Sepet.Add(ms);

        //    db.SaveChanges();
        //    return Redirect("/");
        //}
        //public ActionResult yeni()
        //{
        //    return View();
        //}
        //public ActionResult AddToCart(int ProductId, int adet,decimal Fiyat)
        //{
        //    Sepet ma = new Sepet();
        //    {
        //        ma.MusteriMail = User.Identity.Name;
        //        ma.UrunId = ProductId;
        //        ma.Adet = adet;
        //        ma.UrunFiyat=Fiyat;
        //    };
        //    db.SaveChanges();
        //    return Content("ok"); 
        //}



    }
}

LavornCom/Views/Urunler/Detay.cshtml
@model LavornCom.Models.Urunler
@{
    ViewBag.Title = "Detay";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{Html.RenderAction("Kategoriler", "Home");}

@*@{Html.RenderAction("yeni","Urunler")}*@






<div class="product-details">
    <!--product-details-->
    <div class="col-sm-5">
        <div class="view-product">
            @*@{  LavornCom.Models.lavornDbEntities db = new LavornCom.Models.lavornDbEntities();
                       var resimler = db.Resimler.Where(x => x.UrunId == Model.ResimId);
                   }
                @foreach (var item in resimler)
                {*@
            <img src="/Content/images/home/@Model.ResimUrl" alt="" style="width:auto;height:auto;">
            @*}*@


            <h3>Yakınlaştır</h3>
        </div>
        <div id="similar-product" class="carousel slide" data-ride="carousel">

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="item">
                    <a href=""><img src="/Content/images/product-details/similar1.jpg" alt=""></a>
                    <a href=""><img src="/Content/images/product-details/similar2.jpg" alt=""></a>
                    <a href=""><img src="/Content/images/product-details/similar3.jpg" alt=""></a>
                </div>
                <div class="item">
                    <a href=""><img src="/Content/images/product-details/similar1.jpg" alt=""></a>
                    <a href=""><img src="/Content/images/product-details/similar2.jpg" alt=""></a>
                    <a href=""><img src="/Content/images/product-details/similar3.jpg" alt=""></a>
                </div>
                <div class="item active">
                    <a href=""><img src="/Content/images/product-details/similar1.jpg" alt=""></a>
                    <a href=""><img src="/Content/images/product-details/similar2.jpg" alt=""></a>
                    <a href=""><img src="/Content/images/product-details/similar3.jpg" alt=""></a>
                </div>

            </div>

            <!-- Controls -->
            <a class="left item-control" href="#similar-product" data-slide="prev">
                <i class="fa fa-angle-left"></i>
            </a>
            <a class="right item-control" href="#similar-product" data-slide="next">
                <i class="fa fa-angle-right"></i>
            </a>
        </div>

    </div>
    <div class="col-sm-7">
        <div class="product-information">
            <!--/product-information-->
            @*<img src="/Content/images/product-details@item.ResimUrl" class="newarrival" alt="">*@

            <h5>Ürün Kodu : @Model.Id</h5>
            <h1>@Model.UrunAd</h1>

            <p>Açıklama : @Model.Aciklama </p>
            <p>Kategori : @Model.Kategoriler.KategoriAd</p>

            <p><b>Stok :</b> @Model.Stok</p>
            <p><b>Durum :</b>  Sıfır</p>
            @*<p><b>Size</b> : @Model.Size </p>*@




            <span>
                <span style="color:orange;">Ürün Fiyatı : @Model.UrunFiyat.ToString("#,##0.00") ₺ (KDV Dahil)@*&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                &nbsp;
                &nbsp;*@
              </span>

                @*<input type="text" value="1" style="width:auto;">*@
                @*<input class="wow fadeIndown animated" data-wow-delay=".6s" type="text" Name="Urun" placeholder="@Model.UrunAd " required="">*@

                <form action="/Sepet/SepeteEkle" method="post">

                  
                     <span>

                       
                       
                        <h2 style="color:orange;">Adet : </h2>
                        <select @*style="width:55px;height:55px;"*@ name="adet"class ="btn btn-default dropdown-toggle usa">
                            <option style="width:45px;height:25px;">1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                            <option>6</option>
                            <option>7</option>
                            <option>8</option>
                            <option>9</option>
                            <option>10</option>
                        </select>
                       </span>
                        @*<input type="text" placeholder="1" name="adet" class="form-control">*@
                      <span>
                            <h2 style="color:orange;">Renk : </h2>  
                            @*<input type="text" placeholder="1" name="renk" class="form-control">*@
                        <select  name="renk"class ="btn btn-default dropdown-toggle usa">
                            <option>Mavi</option>
                            <option>Sarı</option>
                            <option>Siyah</option>
                            </select>
                          </span>
                    <span>
                        <h2 style="color:orange;">Size : </h2>
                        <select name="size"class ="btn btn-default dropdown-toggle usa">
                            <option>X</option>
                            <option>S</option>
                            <option>M</option>
                        </select>
                        @*<input type="text" placeholder="1" name="size" class="form-control">*@
                    </span>
                    <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
                    <span>
                        <button type="submit" class="btn btn-fefault cart" style="background-color:orange;color:white;">
                            Sepete Ekle
                        </button>

                    </span>


                            <input type="hidden" name="id" value="@Model.Id" />



                  
            </form>
        </div><!--/product-information-->
    </div>
</div>
               


@*<button type="button" class="btn btn-fefault cart">
        <i class="fa fa-shopping-cart"></i>
        @Html.ActionLink("Sepete At", "SepeteEkle", "Sepet", new { id = Model.UrunId },null)
    </button>*@

@*@{Html.RenderAction("", " ")};*@

<div class="category-tab shop-details-tab">
    <div class="tab-pane fade active in" id="reviews">

        <div class="tab-content">
            <div class="col-sm-12">


                @*@{ Html.RenderAction("YorumlarListe", "Urunler");}*@

                <form action="/Urunler/Yorumlar" method="post">
                    <span>
                        <input type="text" placeholder="İsminiz" name="yorumcuad" class="form-control">
                        <input type="email" placeholder="Mail Adresiniz" name="mailadres" class="form-control">
                        <input type="hidden" placeholder="" name="urunıd" value="@Model.Id" readonly class="form-control">
                    </span>
                    <textarea name="yorum" class="form-control"></textarea>
                    <b>Rating: </b> <img src="/Content/images/product-details/rating.png" alt="">
                    <button type="submit" class="login-form">
                        Gönder
                    </button>

                </form>


            </div>
        </div>
    </div>
</div>
@*@{ Html.RenderAction("Yorumlar", "Urunler");}*@

LavornCom/Views/Urunler/Index.cshtml
@model IEnumerable<LavornCom.Models.Urunler>

@{

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutYeni.cshtml";
}
@*@{ Html.RenderAction("KategorilerLeft", "Home");
}*@

<div class="container body-content">



    <h2>Log in.</h2>
    <div class="row">
        <div class="col-md-8">
            <section id="loginForm">
                <form action="/Account/Login" class="form-horizontal" method="post" role="form" novalidate="novalidate">
                    <input name="__RequestVerificationToken" type="hidden" value="WQrfXCarfn3cK97Wuvi_jQo35YjycEifrirK8WXRru6fG2ho6yFjf_3IAne8DDZHlcihj3wp8FQvGWoVSeVU33p56VGaALCFSBxCV1ipuZ41">                <h4>Use a local account to log in.</h4>
                    <hr>
                    <div class="form-group">
                        <label class="col-md-2 control-label" for="Email">Email</label>
                        <div class="col-md-10">
                            <input class="form-control" data-val="true" data-val-email="Email alanı geçerli bir e-posta adresi değil." data-val-required="Email alanı gereklidir." id="Email" name="Email" type="text" value="">
                            <span class="field-validation-valid text-danger" data-valmsg-for="Email" data-valmsg-replace="true"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label" for="Password">Password</label>
                        <div class="col-md-10">
                            <input class="form-control" data-val="true" data-val-required="Password alanı gereklidir." id="Password" name="Password" type="password">
                            <span class="field-validation-valid text-danger" data-valmsg-for="Password" data-valmsg-replace="true"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <div class="checkbox">
                                <input data-val="true" data-val-required="Remember me? alanı gereklidir." id="RememberMe" name="RememberMe" type="checkbox" value="true"><input name="RememberMe" type="hidden" value="false">
                                <label for="RememberMe">Remember me?</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Log in" class="btn btn-default">
                        </div>
                    </div>
                    <p>
                        <a href="/Account/Register">Register as a new user</a>
                    </p>
                </form>
            </section>
        </div>
        <div class="col-md-4">
            <section id="socialLoginForm">

                <h4>Use another service to log in.</h4>
                <hr>
                <div>
                    <p>
                        There are no external authentication services configured. See <a href="http://go.microsoft.com/fwlink/?LinkId=403804">this article</a>
                        for details on setting up this ASP.NET application to support logging in via external services.
                    </p>
                </div>


            </section>
        </div>
    </div>


    <hr>
    <footer>
        <p>© 2016 - My ASP.NET Application</p>
    </footer>
</div>
<div class="features_items">
    <!--features_items-->
    <h2 class="title text-center">Özel Ürünler</h2>
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <img src="/Content/images/home/product1.jpg" alt="">
                    <h2>$56</h2>
                    <p>Easy Polo Black Edition</p>
                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Satın Al</a>
                </div>
                <div class="product-overlay">
                    <div class="overlay-content">
                        <h2>$56</h2>
                        <p>Easy Polo Black Edition</p>
                        <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Satın Al</a>
                    </div>
                </div>
            </div>
            <div class="choose">
                <ul class="nav nav-pills nav-justified">
                    <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                    <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <img src="/Content/images/home/product2.jpg" alt="">
                    <h2>$56</h2>
                    <p>Easy Polo Black Edition</p>
                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                </div>
                <div class="product-overlay">
                    <div class="overlay-content">
                        <h2>$56</h2>
                        <p>Easy Polo Black Edition</p>
                        <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                    </div>
                </div>
            </div>
            <div class="choose">
                <ul class="nav nav-pills nav-justified">
                    <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                    <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <img src="/Content/images/home/product3.jpg" alt="">
                    <h2>$56</h2>
                    <p>Easy Polo Black Edition</p>
                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                </div>
                <div class="product-overlay">
                    <div class="overlay-content">
                        <h2>$56</h2>
                        <p>Easy Polo Black Edition</p>
                        <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                    </div>
                </div>
            </div>
            <div class="choose">
                <ul class="nav nav-pills nav-justified">
                    <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                    <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <img src="/Content/images/home/product4.jpg" alt="">
                    <h2>$56</h2>
                    <p>Easy Polo Black Edition</p>
                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                </div>
                <div class="product-overlay">
                    <div class="overlay-content">
                        <h2>$56</h2>
                        <p>Easy Polo Black Edition</p>
                        <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                    </div>
                </div>
                <img src="/Content/images/home/new.png" class="new" alt="">
            </div>
            <div class="choose">
                <ul class="nav nav-pills nav-justified">
                    <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                    <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <img src="/Content/images/home/product5.jpg" alt="">
                    <h2>$56</h2>
                    <p>Easy Polo Black Edition</p>
                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                </div>
                <div class="product-overlay">
                    <div class="overlay-content">
                        <h2>$56</h2>
                        <p>Easy Polo Black Edition</p>
                        <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                    </div>
                </div>
                <img src="/Content/images/home/sale.png" class="new" alt="">
            </div>
            <div class="choose">
                <ul class="nav nav-pills nav-justified">
                    <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                    <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <img src="/Content/images/home/product6.jpg" alt="">
                    <h2>$56</h2>
                    <p>Easy Polo Black Edition</p>
                    <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                </div>
                <div class="product-overlay">
                    <div class="overlay-content">
                        <h2>$56</h2>
                        <p>Easy Polo Black Edition</p>
                        <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
                    </div>
                </div>
            </div>
            <div class="choose">
                <ul class="nav nav-pills nav-justified">
                    <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                    <li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
                </ul>
            </div>
        </div>
    </div>

</div>





@{ Html.RenderAction("OnerilenUrunler", "Home"); }

LavornCom/Views/Urunler/Kategoriler.cshtml
@model IEnumerable<LavornCom.Models.Urunler>
@{
    ViewBag.Title = "Kategoriler";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<body>
    <h2 style="color:darkorange">Kategoriler</h2>
    <hr style="border-color:darkorange;border-width :5px" />
    @foreach (var item in Model)
    {


         <div class="col-sm-3">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <img src="~/Content/images/shop/@item.ResimUrl" alt="">
                    <h2>@item.UrunFiyat.ToString("#,##0.00") ₺</h2>
                    <p>@item.UrunAd</p>
                   
                    <a href="~/Urunler/Detay/@item.Id" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>İncele</a>
                </div>

            </div>
        </div>
    </div>
    }
</body>

LavornCom/Views/Urunler/Markalar.cshtml
@model IEnumerable<LavornCom.Models.Urunler>
@{
    ViewBag.Title = "Markalar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="color:darkorange">Markalar</h2>
<hr style="border-color:darkorange;border-width :5px" />

<body>

    @foreach (var item1 in Model)
    {


        <div class="col-sm-3">
            <div class="product-image-wrapper">
                <div class="single-products">
                    <div class="productinfo text-center">
                        <img src="~/Content/images/shop/@item1.ResimUrl" alt="">
                        <h2>@item1.UrunFiyat.ToString("#,##0.00") ₺</h2>
                        <p>@item1.UrunAd</p>

                        <a href="~/Urunler/Detay/@item1.Id" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>İncele</a>
                    </div>

                </div>
            </div>
        </div>
    }
</body>

LavornCom/Views/Urunler/Uyelik.cshtml
@model EmreGiyim.Models.lavornDbENTITY
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-sm-4 col-sm-offset-1">
        <div class="login-form">
            <!--login form-->
            <h2>Giriş Yap</h2>
            <form action="#">
                <input type="text" placeholder="Name">
                <input type="email" placeholder="Email Address">
                <span>
                    <input type="checkbox" class="checkbox">
                    Beni Hatırla
                </span>
                <button type="submit" class="btn btn-default">Giriş Yap</button>
            </form>
        </div><!--/login form-->
    </div>
    <div class="col-sm-1">
        <h2 class="or">Ya Da</h2>
    </div>
    <div class="col-sm-4">
        <div class="signup-form">
            <!--sign up form-->
            <h2>Yeni Üye Ol</h2>
            <form action="#">
                <input type="text" placeholder="Name" id="name">
                <input type="email" placeholder="Email Address" id="email">
                <input type="password" placeholder="Password" id="sifre">
                <button type="submit" class="btn btn-default">Kayıt Ol</button>
            </form>
        </div><!--/sign up form-->
    </div>
</div>

LavornCom/Views/Urunler/Yorumlar.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Yorumunuz Kayıt Edildi.</h1>
<h2>Onaylandığı zaman göstereceğiz.</h2>

LavornCom/Views/Urunler/yeni.cshtml
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "yeni";
    Layout = null;
}

<h2>@User.Identity.Name</h2>