LavornCom/Controllers/SepetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LavornCom.Models;
namespace LavornCom.Controllers
{
    public class SepetController : Controller
    {
        DB_109003_lavornEntities db = new DB_109003_lavornEntities();
        AlisverisSepeti alisverisSepeti;

        public AlisverisSepeti AlisverisSepeti
        {
            get
            {
                if (alisverisSepeti==null)
                {
                    alisverisSepeti = new AlisverisSepeti(this.HttpContext); 
                }
                return alisverisSepeti;


            }
            set
            {
                alisverisSepeti = value;
            }
        }

        public SepetController()
        {

           
          
        }
        // GET: Sepet

        public ActionResult Index()
        {
         
            
            return View(AlisverisSepeti.SepettekiUrunler);
        }
      
        public ActionResult SepeteEkle(int id,int adet,string renk,string size)
        {
          Urunler gelen=  db.Urunler.FirstOrDefault(x => x.Id == id);
            if (gelen!=null)
            {
                
                SepetUrunu urn = new SepetUrunu();
                urn.UrunId = gelen.Id;
                urn.UrunAdı = gelen.UrunAd;
                urn.Adet = adet;
                urn.Fiyat = gelen.UrunFiyat;
                urn.Renk = renk;
                urn.Size = size;

                AlisverisSepeti.SepeteEkle(urn);
            }

           return RedirectToAction("Index");
            
        }
        public ActionResult SepettenKaldir(int id,string renk,string size)
        {
            Urunler gelen = db.Urunler.FirstOrDefault(x => x.Id == id);
            if (gelen!=null)
            {
               

                AlisverisSepeti.SepettenKaldir(gelen.Id,renk,size);
            }
            return RedirectToAction("Index");
        }
        public ActionResult SepetiTemizle()
        {


            AlisverisSepeti.SepetiTemizle();
            return RedirectToAction("Index");
        }
    }
}

LavornCom/Views/Sepet/Index.cshtml
@model IEnumerable<LavornCom.Models.SepetUrunu>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="color:darkorange;">Sepet</h2>
<hr style="border-color:darkorange;border-width:5px" />

<p>
    @*@Html.ActionLink("Create New", "Create")*@
</p>
<div class="table-responsive cart_info">
    <table class="table table-condensed">
        <tr>
            <th class="description">
                Ürünler
                @*@Html.DisplayNameFor(model => model.UrunAdı)*@
               
            </th>
           
            <th class="cart_price">
                @Html.DisplayNameFor(model => model.Fiyat)
            </th>
            <th class="cart_quantity">
                @Html.DisplayNameFor(model => model.Adet)
            </th>
            <th class="cart_quantity">
                @Html.DisplayNameFor(model => model.Renk)
            </th>
            <th class="cart_quantity">
                @Html.DisplayNameFor(model => model.Size)
            </th>
            
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                
                <td class="cart_product">
                
                    @Html.DisplayFor(modelItem => item.UrunAdı)
                  
                </td>
    
                <td class="cart_price">
                    @Html.DisplayFor(modelItem => item.Fiyat)
                   
                </td>
                <td class="cart_quantity">
                    @Html.DisplayFor(modelItem => item.Adet)

                </td>
                <td class="cart_price">
                    @Html.DisplayFor(modelItem=>item.Renk)
                </td>
                <td class="cart_price">
                    @Html.DisplayFor(modelItem => item.Size)
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
                  
                    @Html.ActionLink("Sil", "SepettenKaldir", new { id = item.UrunId })
                 

                </td>
            
            </tr>
        }

    </table>
  @*@Html.ActionLink("Sepeti Boşalt", "SepetiTemizle","Sepet")*@
    <a href="/Sepet/SepetiTemizle">
        <img src="~/Content/images/sepetibosalt.png" style="width:125px;" />
    </a>
    </div>
@{decimal toplam = 0.0m;}
@foreach (var item in Model)
{
    toplam += item.Fiyat * item.Adet;

}
<p class="product-details" style="color:orange;">Sepet Toplamı : @toplam.ToString("#,##0.00") ₺ (KDV Dahil)</p>